### ISSUE TITLE
Inconsistency in grpc metadata mapping

### ISSUE THREAD

**Issue by sysradium** [micro/go-plugins#164] opened 2018-03-23 10:16 UTC
Native grpc metadata object is a `map[string][]string`, however go-micro uses its own `map[string]string` metadata, i.e. it does not understand non-unique http headers.

It looks like you tried to solve that problem by concating values: 
https://github.com/micro/go-plugins/blob/master/server/grpc/grpc.go#L196

However that is ignored here:
https://github.com/micro/go-plugins/blob/master/client/grpc/grpc.go#L55

So in case `client -> service1 -> service2` if client sends:
```
Accept-Language: en
Accept-Language: ru
```
Service2 will receive:
```
Accept-Language: en, ru
```
Maybe we should rewrite go-micro metadata package and start using `map[string][]string`. Does not seem to be that hard.

However it is a breaking change for clients ...

**Comment by asim** [comment] 2018-03-23 12:44
I'm hesitant to make a breaking change like that just because of how many code bases it will likely break. Metadata isn't just a singular type, it gets mapped to headers in the broker and transport. It would be a pretty significant change. 

The fact that we preserve values in comma separated form is quite useful. We can fix the client to split the value back out before sending it via grpc-go/metadata.MD. And additionally include grpc-go/metadata.MD in context so it's accessible if you'd prefer to parse that version.

Thoughts?

**Comment by sysradium** [comment] 2018-03-23 12:55
@asim 
This is fine until someone uses comma the header value. Which is allowed from what I can tell:
```
Some-Header1: a,b
Some-Header2: c
Some-Header2: d
```
Will serialise it as:
```
{"some-header1": "a,b", "some-header2": "c, d"}
```
And then send as:
```
Some-Header1: a
Some-Header1: b
Some-Header2: c
Some-Header2: d
```
Which is wrong.

**Comment by asim** [comment] 2018-03-23 13:02
If I look at http rfcs and whatnot for this, it implies this is the expected behaviour. https://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable

**Comment by sysradium** [comment] 2018-03-23 13:30
Ah, so there is actually no way of sending a comma as a value, not being treated as a separator.
Then probably this means that everything is ok with your code if GRPC metadata functions are smart enough to work both with comma separated and duplicated headers. Because you are sending a "joined" version of metadata.

**Comment by asim** [comment] 2018-04-05 09:07
I am going to close this issue since it seems we're agreed that comma-separated values are fine

**Closed by asim** 2018-04-05 09:07 UTC
