### ISSUE TITLE
integration request: grpc-gateway

### ISSUE THREAD

**Issue by prasannavl** [micro/go-plugins#118] opened 2017-09-01 09:18 UTC
micro is just unbeatable in order to quickly create rpc services. However, while `sidecar` reverse proxy is nice, it's feels like there a lack of polish there and always requires quite a bit of tweaking for it work properly and routing right. 

However, if the core services are grpc based, then grpc-gateway does a fantastic job of quickly converting them into http handler, which can then just be served up on a standard `http` server. It would be terrific if grpc gateway can be integrated for providing a micro `web` entity, and can both can be optionally generated from a single command, when compiling the proto for grpc. 

Compiling a Grpc would in that case, give both a full http proxy, which can be customized with middle wares if needed easily, and the GRPC service. 

https://github.com/grpc-ecosystem/grpc-gateway

**Comment by asim** [comment] 2017-09-01 10:12
The micro api is what's used to route http to rpc. It provides dynamic routing. It's used as the api gateway. If you're thinking about a 1:1 sidecar with your rpc services using a grpc-gateway style generated system that's in the pipeline. I'm currently looking at the best way to do that. We won't specifically integrate the grpc-gateway mostly because its not pluggable and cannot be maintained by us. A micro sidecar generated by protos is likely the next step.

**Comment by asim** [comment] 2017-09-01 10:35
Actually I think you should probably look closer at the micro api to understand how that works. The api has a number of handlers which can be dynamically set along with its auto routing based on namespace and http url path. https://micro.mu/docs/api.html. The go-api library lets you define routes as metadata with your rpc service if you want it to explicitly route certain paths https://github.com/micro/go-api. This is our model for http. The alternative is the sidecar which again has dynamic routing or the micro web component for web apps.

Each of these components is pluggable via a plugin interface https://micro.mu/docs/plugins-toolkit.html. Each of these components also makes use of go-micro which means you can alter the default go-micro client

**Comment by prasannavl** [comment] 2017-09-01 10:37
> 1:1 sidecar with your rpc services using a grpc-gateway style generated system that's in the pipeline

Awesome! That's exactly what I was looking for. To add little more context, we're attempting to move pretty much all our services into micro - which are currently GRPC + gateway - there's no more than a few http middleware wraps for the http code, and I intend to keep it that way. 

micro seems to address all this beautifully, except a consistent gateway that translates everything to json for browser consumption, without writing code manually.

> A micro sidecar generated by protos is likely the next step.

Sounds great. That is indeed what I meant by integrating grpc-gateway. Probably should have phrased it differently. 

Looking forward to see some alpha implementation which I'll be happy help with when I can.

**Comment by prasannavl** [comment] 2017-09-01 10:50
>  I think you should probably look closer at the micro api

That's the direction I took initially. But I certainly didn't look hard enough and had trouble hitting the right routes when I had custom namespaces - and the conventional routing also didn't seem intuitive in some cases. Eg: /hello/greeter/hello, as opposed to "/hello"

Then, instead of trying to get various parts of setting custom namespaces, ensuring the service names, and the service name in the proto definitions, and get all of them right - I was thinking of just using `web`, and wrapping the handler with the grpc-gateway generated ones. (I haven't tried this yet, but was the direction I was hoping to move provided I can reuse the same "srv" service with micro).

**Comment by asim** [comment] 2017-09-01 11:05
The grpc-gateway indicates a 1:1 mapping of a rest proxy to an rpc service. In a microservices architecture this implies if you had 100 microservices you would also have 100 rest proxies. Not only that but the grpc-gateway expects an address:port for the backend rpc service to route to. These might work in a certain context but they do not in the micro ecosystem.

Have a look at the request mapping https://micro.mu/docs/api.html#api-request-mapping. The idea of routing to /hello/greeter/hello is very strange. I'm not sure you would have a service called hello. More likely a service called greeter with the method hello. In which case /greeter/hello would map to go.micro.api.greeter with method Greeter.Hello. The alternative as mentioned is to map a route when writing your rpc service which looks like the following.

```
// Register handler and the endpoint mapping
proto.RegisterGreeterHandler(service.Server(), new(Greeter), api.WithEndpoint(&api.Endpoint{
	// The RPC method
	Name: "Greeter.Hello",
	// The HTTP paths. This can be a POSIX regex
	Path: []string{"/greeter"},
	// The HTTP Methods for this endpoint
	Method: []string{"GET", "POST"},
	// The API handler to use
	Handler: api.Rpc,
})
```

Note here we have said map the http path /greeter to the method Greeter.Hello. 

Micro uses tooling to logically separate responsibilities. This is for scaling purposes both technically and organisationally. We have API, Web and SRV services. If you want to strip all that down you can but we're operating for scale here. Read more about that here https://micro.mu/blog/2016/04/18/micro-architecture.html

Hope that helps a bit. Please join the slack for further discussion http://slack.micro.mu/

Closing the issue for now as the integration is unlikely to happen but the issue is noted and its the next thing in the pipeline, simplifying the http to rpc mapping and actually even further than that we're looking at going language agnostic with the sidecar.

**Closed by asim** 2017-09-01 11:05 UTC
