### ISSUE TITLE
NATS broker implementation does not use address given by Options if set at the Init() call

### ISSUE THREAD

**Issue by darren-west** [micro/go-plugins#100] opened 2017-05-23 16:18 UTC
Hi,

I believe this is a bug. 

The following code will connect to a NATS server on the address specified below:

```
 	b := nats.NewBroker(broker.Addrs("192.168.0.1:5222"))
	b.Init()
	if err := b.Connect(); err != nil {
		log.Fatal(err)
	}
```

If i now change this code to use the Init function it will no longer work, as below:

```
	b := nats.NewBroker()
	b.Init(broker.Addrs("192.168.0.1:5222"))
	if err := b.Connect(); err != nil {
		log.Fatal(err)
	}
```

I dont know if this was your intention, if so is there a reason for this?

The reason this happens is because in the NewBroker method the following happens:

```
	if len(cAddrs) == 0 {
		cAddrs = []string{nats.DefaultURL}
	}
	return &nbroker{
		addrs: cAddrs,
		opts:  options,
	}
```

Which sets the nbroker structs addrs field but in the Init function this field is never set, only the options are configured:

```
func (n *nbroker) Init(opts ...broker.Option) error {
	for _, o := range opts {
		o(&n.opts)
	}
	return nil
}

```

Quite an easy fix, if you agree it is a bug.

Thanks in advance,
I look forward to hearing your opinions,
Darren

**Comment by asim** [comment] 2017-05-23 18:04
It was not a bug but written like that on purpose. User will be left to manage race conditions in calling Init/Connect/Disconnect with the use of addrs without a mutex. PR merged.

**Closed by asim** 2017-05-23 18:04 UTC

**Comment by darren-west** [comment] 2017-05-23 19:08
Thanks. Agreed, but would this not apply to all the broker options?

**Comment by asim** [comment] 2017-05-23 19:11
Yes likely would.

Out of curiosity, where are you using this and at what scale?
