### ISSUE TITLE
grpc context DeadlineExceeded with client-side streaming

### ISSUE THREAD

**Issue by magaldima** [micro/go-plugins#200] opened 2018-07-17 17:54 UTC
I have a bidirectional streaming gRPC protocol and want a client to be able to send on a stream. Once I initialize the stream, my first send (which occurs right after) succeeds. However, if I put a `time.Sleep(6 * time.Second)` after the initialization and then try to send, it fails on the receive side with `rpc error: code = DeadlineExceeded desc = context deadline exceeded`. 

I should expect first that streams do not have a timeout of `5s`. Unlike unary RPC calls, streams should be kept alive until the `ctx` is done. This job of canceling the context or setting deadlines should be left to the client.
I should expect second that if streams have a timeout set, that the send fails with an error while the receive also fails with an error. 

I'm working on debugging through the `grpc` go-plugin to see what I can do to fix this.

Also, the current implementation may have a context leak since the `Stream` is always setup with a context with a deadline in `go-plugins/client/grpc/grpc.go line 357`.

**Comment by magaldima** [comment] 2018-07-17 18:22
I can get around this temporarily by passing in the client.CallOption `client.RequestTimeout(-1)`

**Comment by magaldima** [comment] 2018-07-17 19:46
I propose revising the `Stream` interface methods to allow send and recv to take context params as below:'
```
// Stream is the inteface for a bidirectional synchronous stream
type Stream interface {
	Context() context.Context
	Request() Request
	Send(context.Context, interface{}) error
	Recv(context.Context, interface{}) error
	Error() error
	Close() error
}
```

This way, each send/recv can have it's own context.

**Comment by asim** [comment] 2018-07-17 23:25
PR merged thanks

**Comment by magaldima** [comment] 2018-07-17 23:25
I'm now noticing weird behavior with the grpc streams. Sometimes, the client is able to send all the requests and sometimes the server receives all the requests. The comms do not seem to be consistent and using the same binary different times gives different results... I'm beginning to think there may be another problem I'm running into here with locks...

**Closed by asim** 2018-07-17 23:25 UTC

**Comment by magaldima** [comment] 2018-07-18 12:57
Actually, can we re-open this issue, there seems to be a very similar problem with the non-grpc clients + servers. (This may be relevant to the http plugin, but I certainly know its an issue for the go-micro rpc built-in default)

**Comment by tiger902** [comment] 2019-05-23 10:15
"id":"go.micro.client","code":408,"detail":"call timeout: context deadline exceeded","status":"Request Timeout

**Comment by ZiyunYang** [comment] 2019-08-15 09:38
@tiger902  Hi, have you solved the problem? I meet the same one.

**Comment by tiger902** [comment] 2019-08-15 09:54
> @tiger902 Hi, have you solved the problem? I meet the same one.

My problem was caused by setting up the terminal agent. I cancelled the agent and the problem was solved

**Comment by tiger902** [comment] 2019-08-15 09:55
@ZiyunYang  My problem was caused by setting up the terminal agent. I cancelled the agent and the problem was solved

**Comment by ZiyunYang** [comment] 2019-08-15 10:08
@magaldima @magaldima Hi, I'm new to go-micro and I met several problems. I want to implement a similar feature as you did by using default rpc client+server and NATs registry, NATs streaming broker and NATs transport plugins. My design is that the client implements Call function to get certificates from the server every 5mins. If any certificates changes in server, the server Pub the event to the client and the client Sub the event. 
The problem is when client implements Call function every 30 seconds, it fails on the client side with error: "id":"go.micro.client","code":408,"detail":"call timeout: context deadline exceeded","status":"Request Timeout". This error has nothing to do with the Call interval. And NATs seems to work normal.

My questions are:
* Do you think the cause of the problem is as same as this PR. Or can you give a hint how to debug….
https://github.com/micro/go-plugins/pull/203/commits/24a24f1ebfb3d2b201b6e2a1e11714ef5155c8a0

* Do you think my design is reasonable? Should I consider using gRPC stream since the client and server communicate in both directions. 

Thanks! And looking forward to your reply.

**Comment by ZiyunYang** [comment] 2019-08-15 10:22
@tiger902 Well, my problem is not caused by proxy. Thanks anyway.

**Comment by ZiyunYang** [comment] 2019-08-15 11:00
@magaldima 
Here's my code:
https://github.com/ZiyunYang/yzy_gomicro

**Comment by asim** [comment] 2019-08-15 11:14
Please do not respond to closed issues
