### ISSUE TITLE
etcdv3Watcher.Next()  Delete event not working 

### ISSUE THREAD

**Issue by weisd** [micro/go-plugins#108] opened 2017-07-11 04:37 UTC
i use selector and register only  in my project, but watch delete event not working
```
func (ew *etcdv3Watcher) Next() (*registry.Result, error) {
	for wresp := range ew.w {
		if wresp.Err() != nil {
			return nil, wresp.Err()
		}
		for _, ev := range wresp.Events {
			service := decode(ev.Kv.Value)
			var action string

			switch ev.Type {
			case clientv3.EventTypePut:
				if ev.IsCreate() {
					action = "create"
				} else if ev.IsModify() {
					action = "update"
				}
			case clientv3.EventTypeDelete:
				action = "delete"

				// get the cached value
				ctx, cancel := context.WithTimeout(context.Background(), ew.timeout)
				defer cancel()

				resp, err := ew.client.Get(ctx, path.Join(cachePrefix, string(ev.Kv.Key)))
				if err != nil {
					return nil, err
				}

				for _, ev := range resp.Kvs {
					service = decode(ev.Value)
				}

			}
			if service == nil {
				continue
			}
			return &registry.Result{
				Action:  action,
				Service: service,
			}, nil
		}
	}
	return nil, errors.New("could not get next")
}
```
when get delete event, cachePrefix always get empty, so service == nil , then wait for next event
what the cachePrefix do , and where to set it ?

**Comment by asim** [comment] 2017-07-11 16:21
When a node is deregistered its deleted from etcd and then put in the cache so the watcher can get the exact entity that was deleted. See here https://github.com/micro/go-plugins/blob/master/registry/etcdv3/etcdv3.go#L87.

**Comment by weisd** [comment] 2017-07-11 16:47
@asim so the node must call deregistered function,  what about if the node panic or network err

**Comment by asim** [comment] 2017-07-11 16:55
Yes, there's an expectation of deregistering nodes. In the case of panics you can register with ttl so that nodes are expired. I'm not sure if this will invoke a delete event or not. The way the caching selector is setup, the cache is periodically purged to avoid any staleness caused by the watcher.

**Comment by asim** [comment] 2017-07-18 13:18
Closing as it feels like an issue related to use.

**Closed by asim** 2017-07-18 13:18 UTC
