### ISSUE TITLE
go-plugins failed to build (it happened today)

### ISSUE THREAD

**Issue by skanori** [micro/go-plugins#175] opened 2018-04-30 22:57 UTC
Hi, when ran the go build on our go code, it fails to build the 'go-build',  any pointers to fix ? Thank you. 
--------------------------------
our Gopkg.toml --- content

[[override]]
  name = "github.com/micro/go-micro"
  version = "0.8.0"

[[override]]
  name = "github.com/micro/go-plugins"
  version = "0.10.0"
[[constraint]]
  name = "github.com/micro/go-grpc"
  version = "0.1.0"

[[override]]
  name = "github.com/micro/go-micro"
  version = "0.8.0"

-------------------Error below. 

# github.com/micro/go-plugins/server/grpc
15:49:17 ../../../github.com/micro/go-plugins/server/grpc/grpc.go:257:16: too many arguments in call to t.Write
15:49:17 	have (*"google.golang.org/grpc/transport".Stream, []byte, []byte, *"google.golang.org/grpc/transport".Options)
15:49:17 	want (*"google.golang.org/grpc/transport".Stream, []byte, *"google.golang.org/grpc/transport".Options)
15:49:17 ../../../github.com/micro/go-plugins/server/grpc/grpc.go:261:16: cannot use stream (type *"google.golang.org/grpc/transport".Stream) as type io.Reader in field value:
15:49:17 	*"google.golang.org/grpc/transport".Stream does not implement io.Reader (wrong type for Read method)
15:49:17 		have Read(int) (bool, []byte, error)
15:49:17 		want Read([]byte) (int, error)

**Comment by EwanValentine** [comment] 2018-05-01 08:03
Hey! 

gRPC pushed some changes to their stream implementation last night. It was quite a large change so quite a few changes need to be made to this repo. I think @asim 's looking into it. 

It was this commit https://github.com/grpc/grpc-go/commit/7a8c9895074e03bc7fcff30bd561eaef4fa76dfa

**Comment by asim** [comment] 2018-05-01 12:37
Problem resolved with this commit https://github.com/micro/go-plugins/commit/d30660b6a320e305124d980ff4ff503f7c89451a

**Closed** 2018-05-02 13:41 UTC

**Comment by leon-github** [comment] 2018-05-04 02:26
The problem is happened again as grpc reverted the change a few hour ago. 

==
Revert "Less mem (#1987)" (#2049)
@MakMukhi
MakMukhi committed 8 hours ago

This reverts commit 7a8c989.

**Comment by leon-github** [comment] 2018-05-04 02:28
I think we shall not try to sync up to latest grpc commits. We shall sync up with latest grpc release 1.11.3. I tried with this version of grpc but got the similar problem.

**Comment by MakMukhi** [comment] 2018-05-04 03:11
I'm sorry guys! There were security concerns so we had to revert back that change. Our releases(that happen every six weeks) are more stable than our head.

**Comment by asim** [comment] 2018-05-04 08:49
Seriously uncool. If you don't want it to be used make it internal. You guys make some very terrible breaking changes. I'll go through the effort of writing my own transport or forking entirely. Thanks.

**Comment by MakMukhi** [comment] 2018-05-04 17:40
We do mention it in our [documentation](https://github.com/grpc/grpc-go/blob/b412d5aa54a1f82a55b21f3a8862d6d73baee3d9/transport/transport.go#L21). However, you're right this should have been in an internal package all along. We're looking into doing that now.
