### ISSUE TITLE
GRPC plugin does not work with package names which has dots

### ISSUE THREAD

**Issue by sysradium** [micro/go-plugins#106] opened 2017-06-21 19:00 UTC
It seems that GRPC plugin does not support protofiles which contain dots in their package names.

For example if the full path to the method is `/service.foo.BarStream/GetFaz`
It will fail here: https://github.com/micro/go-plugins/blob/master/server/grpc/grpc.go#L133
With the `malformed method name` error. Was it done on purpose or it is a bug?

**Comment by asim** [comment] 2017-06-21 19:31
Likely a bug. Feel free to PR a fix. Test also welcome.

**Comment by asim** [comment] 2017-07-04 14:18
Is this still an issue? How are these package names being generated? The proto generated converts package names with dots to underscores. Please close if this is a non issue.

**Comment by sysradium** [comment] 2017-07-04 14:27
That's true. If I  remember correctly the problem appears when you are trying to call `go-micro` service from `non-gomicro` service. Because if you generate the protofiles using golang plugin it will just take the proto package name as is, in our case with dots and use it as full path, breaking URL parsing.

The go-micro GRPC client plugin composes the URL on the fly and it uses the golang generated package name, where there are no dots.

That's why I don't know whether it is a bug or not. I would rather assume that the URL is `package_name.service_name/method_name`, where `package_name` might contain dots, but service name and method can not.

**Comment by asim** [comment] 2017-07-04 14:57
The issue is now resolved with this commit https://github.com/micro/go-plugins/commit/893648c1bd6846b46bc82f91a913080f59736f27

Looking at the grpc spec it appears dotted paths are possible http://www.grpc.io/docs/guides/wire.html

Please close if satisfied.

**Closed** 2017-07-08 15:53 UTC
