### ISSUE TITLE
The K8s watcher Continuously returns an error “result chan closed”，causes high CPU usage

### ISSUE THREAD

**Issue by Aavon** [micro/go-plugins#169] opened 2018-04-18 08:23 UTC
the code 
github.com/micro/go-plugins/registry/kubernetes/watcher.go
```
// Next will block until a new result comes in
func (k *k8sWatcher) Next() (*registry.Result, error) {
	r, ok := <-k.next
	if !ok {
		return nil, errors.New("result chan closed")
	}
	return r, nil
}

```

Before，all the service work well
But recently, when the service increased to a certain amount，the Next method return error.It seems the next chan is always closed;
The result is go-rcache is in an endless loop, and it`s the same with the go-api/router

```
// run starts the cache watcher loop
// it creates a new watcher if there's a problem
func (c *cache) run() {
	for {
		// exit early if already dead
		if c.quit() {
			return
		}

		// create new watcher
		w, err := c.Registry.Watch()
		if err != nil {
			if c.quit() {
				return
			}
			log.Log("rcache: ", err)
			time.Sleep(time.Second)
			continue
		}

		// watch for events
		if err := c.watch(w); err != nil {
			if c.quit() {
				return
			}
			log.Log("rcache: ", err)
			// time.Sleep(time.Second)
			continue
		}
	}
}

```

these endless loop cause very high CPU usage ,even cause k8s node unavailable（without the limits）

Is there any probable reason which cause the next chan  closed?

Thanks

**Comment by asim** [comment] 2018-04-18 08:30
If the watcher is stopped and the Next is still called then it will cause this to occur. If the k8s api is terminating the connection then this may also be causing an issue. Have their been any other changes beyond adding new services?

**Comment by Aavon** [comment] 2018-04-18 08:44
nothing else, and the whole kubernetes platform should work right,and the registry have register the service,all services can be called.but beacause the high cpu usage,they are always timeout.

the code 

```
go func() {
		for event := range watcher.ResultChan() {
			k.handleEvent(event)
		}
		k.Stop()
	}()

```

it seems the k.Stop close the chan, and the loop is not blocked,  ResultChan is closed maybe.

**Comment by asim** [comment] 2018-04-18 12:27
You're right. This behaviour is not ideal. I need to look deeper into the code to see how this can be fixed.

**Comment by asim** [comment] 2018-04-18 13:09
Ok so looking into the code. Watching basically involves making a http connection to the k8s api and having it stream back http responses over the connection as updates occur. If this connection dies for some reason (maybe timeout related) then the ResultChan is closed. 

Once the ResultChan is closed that watcher is essentially rendered useless so it stops itself and this propagates the error upstream. In go-rcache we're just looping trying to create a new watcher to go through the process of reconnecting. The solution is to really understand why the connection is breaking, likely k8s api timeout setting related or something in front causing it. In go-rcache I'll look to implement exponential backoff with jitter which will at least not cause high load and provide a greater chance of recovery.

**Comment by asim** [comment] 2018-04-18 16:58
Added backoff/jitter to rcache https://github.com/micro/go-rcache/commit/a581a57b513351792b9f21fc8b95d87b1c5a95da

Please let me know if this helps. I'm thinking your k8s issue is load related.

**Comment by clanstyles** [comment] 2018-04-18 20:46
I've been running into this too. I'll dig into it ri ght now and see if I can figure out what's going on.

**Comment by clanstyles** [comment] 2018-04-18 22:40
After digging into it, so far I can tell it's occurring from the k8s registry plugin. https://github.com/micro/go-plugins/blob/master/registry/kubernetes/watcher.go#L191

I'm guessing that it's disconnecting from k8s and closing the channel without a retry policy?

**Comment by clanstyles** [comment] 2018-04-19 07:06
I don't think it's load related at all. I am booting up a single minikube instance. Blank install, and still experience it.

I am not too familiar with the new k8s network policies, RBAC, etc.. I'm wondering if something else is interfering.

**Comment by asim** [comment] 2018-04-19 07:08
What version of minikube/k8s? If the issue is reproducible then we can debug and see where the problem lies. It could very well be a problem with connecting to the k8s api.

**Comment by Aavon** [comment] 2018-04-19 08:44
I used k8s v1.8.3 on rancher 1.6.12(....)
In my dev env，this problem has only recently emerged，the micro work fine before.Even with the high overhead，the micro can work slowly.Services can correctly de/register. Maybe I need more tests on the k8s api.
And I think  @clanstyles  should  be the same problem with me .
I`ll do more test to get results...

**Comment by asim** [comment] 2018-04-19 08:48
Does the issue go away if you scale back? Did you update the environment in any way?

**Comment by Aavon** [comment] 2018-04-19 08:58
it seems not.I try a new node with less srv . My friend tried locally  mikube(1.10) .He gets high usage issue too...I now have no idea and not want to mislead you.
Could it  be our own code causing the issue?

**Comment by clanstyles** [comment] 2018-04-19 08:58
```
minikube version: v0.25.2
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

Doing some more tests, I removed everything. I stripped the installation back to the following:

```
        env:
          - name: MICRO_BROKER
            value: "http"
          - name: MICRO_REGISTRY
            value: "etcd"
          - name: MICRO_TRANSPORT
            value: "http"
          - name: MICRO_REGISTRY_ADDRESS
            value: "http://etcd.default.svc.cluster.local:2379"
```

I'm still having issues. However, the CLI and the API are not in sync.

```
kubectl exec -it micro-api-7f8994d6f5-lxbvf /bin/sh
/ # micro cli
/bin/sh: micro: not found
/ # /micro cli

micro> list
go.micro.api
go.micro.api.merchant
go.micro.svc.merchant
```

@Aavon check your CLI, do you see your services there, but the API is still failling?

**Comment by clanstyles** [comment] 2018-04-19 08:59
@Aavon what broker, registry, transport, selector, are you using?

**Comment by Aavon** [comment] 2018-04-19 09:05
@clanstyles all my services can work ,but because of the high usage, always time out Or chan closed.
Broker: nats
Registry: k8s
transport:gRpc
selector:cache

**Comment by Aavon** [comment] 2018-04-19 09:11
```
2018/04/19 09:02:52 Registering node: go.micro.api-713663d4-43b0-11e8-8b7e-0250587358ce
2018/04/19 09:02:52 214create watcher
2018/04/19 09:02:52 220k8skubernetes
2018/04/19 09:02:52 scan__ bufio.Scanner: token too long
```
**token too long**
I get the log when read api response

file:github.com/micro/go-plugins/registry/kubernetes/client/watch/body.go
method:func (wr *bodyWatcher) stream() 
Any idea?
Thanks

**Comment by Aavon** [comment] 2018-04-19 09:25
https://github.com/kubernetes/kubernetes/issues/19603

let me tset this first..

I fact , my service interface define increase too. And microwill set the define into the yaml

**Comment by asim** [comment] 2018-04-19 10:26
Ah good spot. This will be causing some major issues which we need to deal with.

**Comment by Aavon** [comment] 2018-04-19 12:26
After stopping the large definition service the error disappeared

but i still get the another error 
```
scan__ read tcp 10.42.209.33:34432-&gt;10.43.0.1:443: use of closed network connection
```
Is the metadate in the pod label really necessary?
```
"micro.mu/service-SERVICE_NAME": some thing like interface define
```
Now,I am thinking change to another Service Discovery is a good choice.An independent SD  will not rely on ths k8s network too much and ignore the max line length issue.And to aplly the CRD may need a lot of extra work.

If you have any other ideas,please make me known ,thanks!

**Comment by asim** [comment] 2018-04-19 12:32
Is the use of closed network connection error appearing because you've modified the code to not stop the watcher when results are finished?

The k8s registry was written 2 years ago when we wanted a way to have zero dependencies and include feature rich metadata. This information is required for wider use with micro. 

You do not have to use the kubernetes registry. You can very easily replace this with the noop registry and use the static selector which will offload load balancing to k8s DNS

**Comment by Aavon** [comment] 2018-04-19 13:38
I import the noop and static plugin.But it not work...

**Comment by asim** [comment] 2018-04-19 13:48
Doc for the static selector https://github.com/micro/go-plugins/tree/master/selector/static

More info on load balancing with the static selector https://github.com/micro/kubernetes#load-balancing

The static selector returns the name you pass in e.g `foo` returns the node `foo:8080`. It then expects a k8s service `foo` with port 8080 exposed which maps to the backend pods. You need to create a k8s service per microservice that you deploy for this to work.

The alternative is to use a different registry or find a way to improve the current kubernetes registry implementation to support services with larger metadata stored.

**Comment by asim** [comment] 2018-04-19 14:50
This is an extremely simple change. Scanner only has a small buffer. Using ReadBytes we can now process events of any length. The fix is here https://github.com/micro/go-plugins/commit/9b10555db387d20915d32fcb13023e29a7df05e4

I'm closing this issue as it solves the problem.

**Closed by asim** 2018-04-19 14:50 UTC

**Comment by Aavon** [comment] 2018-04-20 02:38
Thanks for your commit !
I change the client config to solve the connection close issue when no event to watching.
```
// the same with another client
tr := &http.Transport{
		TLSClientConfig:    &tls.Config{},
		DisableCompression: true,
		MaxIdleConnsPerHost: 1024,
 		TLSHandshakeTimeout: 0 * time.Second,
	}

```
the k8s registry problem resolved.

I tried the noop and static . it seems not work for micro api which use the cache default but the registry  doing nothing.
